COMMISSIONS = 0.0007

MINUTES_IN_A_YEAR = 525949

TAX_RATE = 0.34

PARTIAL_LEVERAGED_SYMBOLS = ("BULL", "BEAR", "HEDGE", "HALF")
NON_USD_FIAT_CURRENCIES = ("EUR", "GBP", "CAD", "SGD")
ORDERBOOK_STEP_SIZE = 0.0001
ASKS_AND_BIDS = ("asks", "bids")
