DATA_STORAGE_LOCATION = "/media/joona/Seagate Expansion Drive"
LOCAL_DATA_DIR = "data"

COMMISSIONS = 0.0007

MINUTES_IN_A_YEAR = 525949

TAX_RATE = 0.34

PARTIAL_LEVERAGED_SYMBOLS = ("BULL", "BEAR", "HEDGE", "HALF")
NON_USD_FIAT_CURRENCIES = ("EUR", "GBP", "CAD", "SGD", "AUD")
ORDERBOOK_STEP_SIZE = 0.0001
ASKS_AND_BIDS = ("asks", "bids")

PRICE_DATA_MAX_GAP = 10

MIN_AGGREGATE_N = 2
MIN_W = 1

LRU_CACHE_MAX_SIZE = 50

MAX_NUMBER_OF_SIMULTANEOUS_STRATEGIES = 20
MAX_TAKE_PROFIT = 100.0
